User.create(username:"JW", email: "123@testing.com", password: "12345")
User.create(username:"OM", email: "123@testing.com", password: "12345")
User.create(username:"CL", email: "123@testing.com", password: "12345")
User.create(username:"KL", email: "123@testing.com", password: "12345")

Cart.create(user_id: 1)
Cart.create(user_id: 2)
Cart.create(user_id: 3)
Cart.create(user_id: 4)

Product.create(title: "straw hat", price: 5, description: "new", image: "https://dmp0bw3rmgwlj.cloudfront.net/catalog/product/cache/2d30c628ca84d1fb5bde9dd708affbe5/r/1/r11_teastain_b_1.jpg", category: "Apparel", user_id: 1)
Product.create(title: "baseball tee", price: 10, description: "new", image: "https://lp2.hm.com/hmgoepprod?set=quality[79],source[/b3/49/b349d9e57192a24357906baa2ac8d29ef255eb98.jpg],origin[dam],category[men_tshirtstanks_shortsleeve],type[DESCRIPTIVESTILLLIFE],res[m],hmver[1]&call=url[file:/product/main]", category: "Apparel", user_id: 1)
Product.create(title: "infinity scarf", price: 10, description: "new", image: "https://www.fjallraven.com/globalassets/catalogs/fjallraven/f7/f780/f78011/f020/7323450521189_fw19_a_solid_rewool_scarf_fjaellraeven_21.jpg?width=2000&height=2000&mode=BoxPad&bgcolor=fff&quality=80", category: "Apparel", user_id: 2)
Product.create(title: "quilted jacket", price: 40, description: "new", image: "https://images-na.ssl-images-amazon.com/images/I/71vpN1h03PL._AC_UY679_.jpg", category: "Apparel", user_id: 2)
Product.create(title: "crew neck sweater", price: 20, description: "worn", image: "https://s7d2.scene7.com/is/image/aeo/0745_1572_231_f?$PDP-1910L$", category: "Apparel", user_id: 3)
Product.create(title: "laptop", price: 500, description: "new", image: "https://i.dell.com/sites/csimages/Video_Imagery/all/xps_7590_touch.png", category: "electronics", user_id: 3)

UserProduct.create(user_id: 1, product_id: 1)
UserProduct.create(user_id: 1, product_id: 2)
UserProduct.create(user_id: 2, product_id: 3)
UserProduct.create(user_id: 2, product_id: 4)
UserProduct.create(user_id: 3, product_id: 5)
UserProduct.create(user_id: 3, product_id: 6)

Review.create(content: "The item came in amazing condition", user_id: 1, product_id: 4)
Review.create(content: "This kept me warm all winter long!", user_id: 1, product_id: 3)
Review.create(content: "The user shipped it earlier than expected. I would recommend anyone check out this user!", user_id: 2, product_id: 6)
Review.create(content: "This became my favorite sweater!", user_id: 2, product_id: 5)
Review.create(content: "Great laptop for anyone who needs a new computer!", user_id: 4, product_id: 6)
Review.create(content: "I've gotten many compliments on this!", user_id: 4, product_id: 1)
